agentgateway:
  enabled: false
controller:
  logLevel: info
# discoveryNamespaceSelectors:
# - matchExpressions:
#   - key: environment
#     operator: In
#     values:
#     - prod
#   matchLabels:
#     version: v2
# - matchLabels:
#     version: v3